apiVersion: v1
kind: ConfigMap
metadata:
  name: rps-config
  namespace: rock-paper-scissors
data:
  FRONTEND_URL: "http://rps-frontend-svc:3000"
  RABBITMQ_URL: "amqp://rps_user:rps_password@rps-rabbitmq-svc:5672/rps_vhost"
  PORT: "3001"
  NEXT_PUBLIC_API_URL: "http://rps-nginx-svc/api"
  NEXT_PUBLIC_WS_URL: "http://rps-nginx-svc"
