apiVersion: v1
kind: Secret
metadata:
  name: rps-secrets
  namespace: rock-paper-scissors
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: rps_user
  RABBITMQ_DEFAULT_PASS: rps_password
  RABBITMQ_DEFAULT_VHOST: rps_vhost
